[project]
name = "ibkr-to-irpf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.123.9",
    "jinja2>=3.1.6",
    "pytest>=9.0.1",
    "ruff>=0.14.8",
]

[tool.pytest]
python_files = ["tests.py"]
